services:
  # ---------------- MONGO DATABASE ------------------------
  # mongodb:
  #   image: mongo:latest
  #   env_file: .env
  #   volumes:
  #     - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #     - ./data/mongodb:/data/db
  #   restart: always

  # mongo-express:
  #   image: mongo-express:latest
  #   depends_on:
  #     - mongodb
  #   env_file: .env
  #   ports:
  #     - "8081:8081"
  #   restart: always

  # ---------------- Services ----------------
  backend:
    build: ./backend
    env_file: .env
    restart: always
    ports:
      - "8082:8082"
